"""modified emialembedding

Revision ID: 627e697c7909
Revises: 818b7f09218f
Create Date: 2026-02-28 16:45:06.305755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '627e697c7909'
down_revision: Union[str, Sequence[str], None] = '818b7f09218f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_embeddings', 'is_sent_by_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_embeddings', sa.Column('is_sent_by_user', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
