"""update google login and access

Revision ID: 8040ba2a9180
Revises: e16e60b74631
Create Date: 2026-02-28 12:56:35.314804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8040ba2a9180'
down_revision: Union[str, Sequence[str], None] = 'e16e60b74631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_embeddings', sa.Column('is_sent_by_user', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user_emails', ['message_id'])
    op.add_column('users', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_token_expiry', sa.DateTime(), nullable=True))
    op.alter_column('users', 'google_refresh_token',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'google_refresh_token',
               existing_type=sa.String(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.drop_column('users', 'google_token_expiry')
    op.drop_column('users', 'google_access_token')
    op.drop_constraint(None, 'user_emails', type_='unique')
    op.drop_column('email_embeddings', 'is_sent_by_user')
    # ### end Alembic commands ###
