"""modified emials

Revision ID: 818b7f09218f
Revises: ab378f9e3276
Create Date: 2026-02-28 14:17:19.871762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '818b7f09218f'
down_revision: Union[str, Sequence[str], None] = 'ab378f9e3276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_emails', sa.Column('is_sent_by_user', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_emails', 'is_sent_by_user')
    # ### end Alembic commands ###
